repository:
    description: Manage your GitHub repository via source control!
    has_wiki: false

    default_branch: master
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: true

collaborators:
    -   username: mattsb42-aws
        permission: admin
    -   username: mattsb42-bot
        permission: push
    -   username: mattsb42-admin-bot
        permission: admin

labels:
    # Default labels
    -   name: bug
        color: d73a4a
        description: Something isn't working
    -   name: duplicate
        color: cfd3d7
        description: This issue or pull request already exists
    -   name: enhancement
        color: a2eeef
        description: New feature or request
    -   name: good first issue
        color: 7057ff
        description: Good for newcomers
    -   name: help wanted
        color: 008672
        description: Extra attention is needed
    -   name: invalid
        color: e4e669
        description: This doesn't seem right
    -   name: question
        color: d876e3
        description: Further information is requested
    -   name: wontfix
        color: ffffff
        description: This will not be worked on

branches:
    -   name: development
        protection:
            required_pull_request_reviews:
                required_approving_review_count: 1
                dismiss_stale_reviews: true
            restrictions: null
            enforce_admins: true
            required_status_checks:
                strict: true
                contexts:
                    - static analysis / analysis (bandit)
                    - local tests
    -   name: master
        protection:
            required_pull_request_reviews: null
            restrictions: null
            enforce_admins: true
            required_status_checks:
                strict: true
                contexts:
                    - static analysis / analysis (bandit)
                    - local tests
