# This workflow runs static analysis checks.
name: static analysis

on: [pull_request]

jobs:
    analysis:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                stage:
                    - lint
                    - mypy
                    - bandit
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-python@v1
                with:
                    python-version: 3.x
            -   run: |
                    python -m pip install --upgrade pip
                    pip install --upgrade -r ci-requirements.txt
            -   name: check
                env:
                    TOXENV: ${{ matrix.stage }}
                run: tox -- -vv
